### ISSUE TITLE
search experience catalog

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#134]
As a traveller, I can search for an experience catalog item, so that I can find something I'm interested in experiencing.

**Acceptance criteria**

* The traveller can enter free text form
* The traveller should specify location for the search
* The traveller should specify start and end date for the search
* The traveller can filter on specific experience category to use (e.g. dining or tours, or all)
* The traveller can sort by alphabetical and reverse alphabetical order, as well as pricing on the ticket item if applicable

**Future considerations**

* Ability to reuse previous searches
* Ability to use popular searches
* Ability to predict what the traveller is typing
* Ability to actively shortlist results based on what the traveller is typing

**Error messages:**

* The system should let the traveller know if there are no searches matching their set criteria. Stretch is that is provides idea on how to make it render results (e.g. you date range is too narrow)
* The system should be able to fail gracefully if something goes wrong while fetching results and allow the traveller to retry

**UX considerations:**
see wireframes in the corresponding epic

**Tech considerations:**
TBD

**QA considerations:**
TBD

**Comment by willmero** [comment]
Could it be possible to add the ability to pass in an array of dates to search the catalog for instead of a fixed start and end date? I imagine with an app that allows you to plan multiple trips, that span different date ranges, that you would want to return catalog items for those date ranges with the recommendation engine running on them, instead of pinging the API 3 separate times for 3 separate date ranges. Recommended arrays would be returned disjointed instead of unified.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
