### ISSUE TITLE
Major|App Crashes after selecting CheckOut button

### ISSUE THREAD

**Issue by kaurmandie** [Guestlogix/traveler-ios#234]
Build version 0.3(72)

Steps :

1) Select any available experience on the home screen and proceed with the booking

2)On the Experience questions screen ,answer all the mandate questions.

3) Tap on Checkout button

Issue - App Crash is observed

Expected - Review Order screen should be displayed

**Comment by dorothyfu** [comment]
- This issue is only revealed because of the issue with the API where it returns 0 instead of a string for purchaseStrategy. Our app throws a mapping error since it does not match to our model but the error in (Traveler.swift)
```public static func createOrder(bookingForm: BookingForm, delegate: OrderCreateDelegate) {
        shared?.createOrder(bookingForm: bookingForm, completion: { [weak delegate] (order, error) in
            if let order = order {
                delegate?.orderCreationDidSucceed(order)
            } else {
                delegate?.orderCreationDidFail(error!)
            }
        })
    }```
is nil and so it tries to unwrap a null value. The error is not getting set properly RemoteFetchOperation.swift

**Comment by kaurmandie** [comment]
No more Crashes observed on Check Out.
